name: Build EXE

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version to use (default: 3.12)"
        default: "3.12"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Poppler
        run: |
          curl -L -o poppler.zip https://github.com/oschwartz10612/poppler-windows/releases/download/v24.08.0-0/Release-24.08.0-0.zip
          unzip poppler.zip -d poppler
          $env:PATH = "$PWD\poppler\Library\bin;$env:PATH"

      - name: Verify Poppler
        run: pdftocairo -v

      - name: Install Python and PyInstaller
        uses: actions/setup-python@v2
        with:
          python-version: '${{ inputs.python-version }}'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller pdf2imageconverter.spec

      # DIST 配下の ZIP 生成物を動的アップロード
      - name: Find and Upload ZIP
        run: |
          VERSION=$(cat version.txt)
          ZIP_FILE="dist/pdf2imageconverter-ver${VERSION}.zip"
          echo "::set-output name=zip_name::${ZIP_FILE}"
        id: set-output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-exe-zip
          path: ${{ steps.set-output.outputs.zip_name }}

